name: events_docker
services:
  events_model.backend:
    image: ${DOCKER_REGISTRY-}eventsmodelbackend
    container_name: events-api
    build:
      context: ./Events_Model_Back
      dockerfile: Events_Model_Back/Events_Model.BackEnd/Dockerfile
    depends_on:
      - sqlserver  

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: events-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1444:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  # events_model.frontend:
  #   container_name: events-web
  #   build:
  #     context: ./Events_Model_Front 
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:80" 
  #   depends_on:
  #     - events_model.backend

volumes:
  sqlserverdata: