// <auto-generated />
using System;
using Events_Model.BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Events_Model.BackEnd.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Events_Model.BackEnd.Models.Event", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvent"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEvent");

                    b.HasIndex("Date");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            IdEvent = 1,
                            Date = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 1.",
                            Title = "Evento Musical #1"
                        },
                        new
                        {
                            IdEvent = 2,
                            Date = new DateTime(2026, 5, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 2.",
                            Title = "Evento Musical #2"
                        },
                        new
                        {
                            IdEvent = 3,
                            Date = new DateTime(2026, 5, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 3.",
                            Title = "Evento Musical #3"
                        },
                        new
                        {
                            IdEvent = 4,
                            Date = new DateTime(2026, 5, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 4.",
                            Title = "Evento Musical #4"
                        },
                        new
                        {
                            IdEvent = 5,
                            Date = new DateTime(2026, 5, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 5.",
                            Title = "Evento Musical #5"
                        },
                        new
                        {
                            IdEvent = 6,
                            Date = new DateTime(2026, 5, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 6.",
                            Title = "Evento Musical #6"
                        },
                        new
                        {
                            IdEvent = 7,
                            Date = new DateTime(2026, 5, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 7.",
                            Title = "Evento Musical #7"
                        },
                        new
                        {
                            IdEvent = 8,
                            Date = new DateTime(2026, 5, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 8.",
                            Title = "Evento Musical #8"
                        },
                        new
                        {
                            IdEvent = 9,
                            Date = new DateTime(2026, 5, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 9.",
                            Title = "Evento Musical #9"
                        },
                        new
                        {
                            IdEvent = 10,
                            Date = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 10.",
                            Title = "Evento Musical #10"
                        },
                        new
                        {
                            IdEvent = 11,
                            Date = new DateTime(2026, 5, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 11.",
                            Title = "Evento Musical #11"
                        },
                        new
                        {
                            IdEvent = 12,
                            Date = new DateTime(2026, 5, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 12.",
                            Title = "Evento Musical #12"
                        },
                        new
                        {
                            IdEvent = 13,
                            Date = new DateTime(2026, 5, 13, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 13.",
                            Title = "Evento Musical #13"
                        },
                        new
                        {
                            IdEvent = 14,
                            Date = new DateTime(2026, 5, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 14.",
                            Title = "Evento Musical #14"
                        },
                        new
                        {
                            IdEvent = 15,
                            Date = new DateTime(2026, 5, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 15.",
                            Title = "Evento Musical #15"
                        },
                        new
                        {
                            IdEvent = 16,
                            Date = new DateTime(2026, 5, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 16.",
                            Title = "Evento Musical #16"
                        },
                        new
                        {
                            IdEvent = 17,
                            Date = new DateTime(2026, 5, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 17.",
                            Title = "Evento Musical #17"
                        },
                        new
                        {
                            IdEvent = 18,
                            Date = new DateTime(2026, 5, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 18.",
                            Title = "Evento Musical #18"
                        },
                        new
                        {
                            IdEvent = 19,
                            Date = new DateTime(2026, 5, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 19.",
                            Title = "Evento Musical #19"
                        },
                        new
                        {
                            IdEvent = 20,
                            Date = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del evento 20.",
                            Title = "Evento Musical #20"
                        });
                });

            modelBuilder.Entity("Events_Model.BackEnd.Models.EventLocation", b =>
                {
                    b.Property<int>("IdLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocation"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.HasKey("IdLocation");

                    b.HasIndex("IdEvent")
                        .IsUnique();

                    b.ToTable("EventLocation");

                    b.HasData(
                        new
                        {
                            IdLocation = 1,
                            Address = "Sede Principal - Auditorio 1",
                            IdEvent = 1,
                            Lat = 4.7120000000000006,
                            Lng = -74.073000000000008
                        },
                        new
                        {
                            IdLocation = 2,
                            Address = "Sede Principal - Auditorio 2",
                            IdEvent = 2,
                            Lat = 4.7130000000000001,
                            Lng = -74.073999999999998
                        },
                        new
                        {
                            IdLocation = 3,
                            Address = "Sede Principal - Auditorio 3",
                            IdEvent = 3,
                            Lat = 4.7140000000000004,
                            Lng = -74.075000000000003
                        },
                        new
                        {
                            IdLocation = 4,
                            Address = "Sede Principal - Auditorio 4",
                            IdEvent = 4,
                            Lat = 4.7149999999999999,
                            Lng = -74.076000000000008
                        },
                        new
                        {
                            IdLocation = 5,
                            Address = "Sede Principal - Auditorio 5",
                            IdEvent = 5,
                            Lat = 4.7160000000000002,
                            Lng = -74.076999999999998
                        },
                        new
                        {
                            IdLocation = 6,
                            Address = "Sede Principal - Auditorio 6",
                            IdEvent = 6,
                            Lat = 4.7170000000000005,
                            Lng = -74.078000000000003
                        },
                        new
                        {
                            IdLocation = 7,
                            Address = "Sede Principal - Auditorio 7",
                            IdEvent = 7,
                            Lat = 4.718,
                            Lng = -74.079000000000008
                        },
                        new
                        {
                            IdLocation = 8,
                            Address = "Sede Principal - Auditorio 8",
                            IdEvent = 8,
                            Lat = 4.7190000000000003,
                            Lng = -74.079999999999998
                        },
                        new
                        {
                            IdLocation = 9,
                            Address = "Sede Principal - Auditorio 9",
                            IdEvent = 9,
                            Lat = 4.7200000000000006,
                            Lng = -74.081000000000003
                        },
                        new
                        {
                            IdLocation = 10,
                            Address = "Sede Principal - Auditorio 10",
                            IdEvent = 10,
                            Lat = 4.7210000000000001,
                            Lng = -74.082000000000008
                        },
                        new
                        {
                            IdLocation = 11,
                            Address = "Sede Principal - Auditorio 11",
                            IdEvent = 11,
                            Lat = 4.7220000000000004,
                            Lng = -74.082999999999998
                        },
                        new
                        {
                            IdLocation = 12,
                            Address = "Sede Principal - Auditorio 12",
                            IdEvent = 12,
                            Lat = 4.7229999999999999,
                            Lng = -74.084000000000003
                        },
                        new
                        {
                            IdLocation = 13,
                            Address = "Sede Principal - Auditorio 13",
                            IdEvent = 13,
                            Lat = 4.7240000000000002,
                            Lng = -74.085000000000008
                        },
                        new
                        {
                            IdLocation = 14,
                            Address = "Sede Principal - Auditorio 14",
                            IdEvent = 14,
                            Lat = 4.7250000000000005,
                            Lng = -74.085999999999999
                        },
                        new
                        {
                            IdLocation = 15,
                            Address = "Sede Principal - Auditorio 15",
                            IdEvent = 15,
                            Lat = 4.726,
                            Lng = -74.087000000000003
                        },
                        new
                        {
                            IdLocation = 16,
                            Address = "Sede Principal - Auditorio 16",
                            IdEvent = 16,
                            Lat = 4.7270000000000003,
                            Lng = -74.088000000000008
                        },
                        new
                        {
                            IdLocation = 17,
                            Address = "Sede Principal - Auditorio 17",
                            IdEvent = 17,
                            Lat = 4.7280000000000006,
                            Lng = -74.088999999999999
                        },
                        new
                        {
                            IdLocation = 18,
                            Address = "Sede Principal - Auditorio 18",
                            IdEvent = 18,
                            Lat = 4.7290000000000001,
                            Lng = -74.090000000000003
                        },
                        new
                        {
                            IdLocation = 19,
                            Address = "Sede Principal - Auditorio 19",
                            IdEvent = 19,
                            Lat = 4.7300000000000004,
                            Lng = -74.091000000000008
                        },
                        new
                        {
                            IdLocation = 20,
                            Address = "Sede Principal - Auditorio 20",
                            IdEvent = 20,
                            Lat = 4.7309999999999999,
                            Lng = -74.091999999999999
                        });
                });

            modelBuilder.Entity("Events_Model.BackEnd.Models.EventLocation", b =>
                {
                    b.HasOne("Events_Model.BackEnd.Models.Event", null)
                        .WithOne("Location")
                        .HasForeignKey("Events_Model.BackEnd.Models.EventLocation", "IdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Events_Model.BackEnd.Models.Event", b =>
                {
                    b.Navigation("Location")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
